// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (c) 2026 Huawei Technologies Co., Ltd. All Rights Reserved.

#ifndef VLLM_ASCEND_FAMEM_PROTOCOL_H
#define VLLM_ASCEND_FAMEM_PROTOCOL_H

#include <stdint.h>

#define FAMEM_PROTOCOL_MAGIC UINT32_C(0x46414D45)
#define FAMEM_PROTOCOL_VERSION UINT16_C(5)
#define FAMEM_PROTOCOL_HEADER_SIZE 24U
#define FAMEM_PROTOCOL_MAX_PAYLOAD 4096U

#define FAMEM_MESSAGE_REQUEST UINT16_C(1)
#define FAMEM_MESSAGE_RESPONSE UINT16_C(2)

#define FAMEM_STATUS_OK UINT32_C(0)
#define FAMEM_STATUS_PROTOCOL UINT32_C(1)
#define FAMEM_STATUS_BUSY UINT32_C(2)
#define FAMEM_STATUS_PERMISSION UINT32_C(3)
#define FAMEM_STATUS_INTERNAL UINT32_C(4)

#define FAMEM_OP_HELLO UINT16_C(1)
#define FAMEM_OP_ACQUIRE UINT16_C(2)
#define FAMEM_OP_SLEEP UINT16_C(3)
#define FAMEM_OP_WAKE UINT16_C(4)
#define FAMEM_OP_RELEASE UINT16_C(5)

#define FAMEM_HELLO_REQUEST_SIZE 72U
#define FAMEM_SESSION_U64_REQUEST_SIZE 40U
#define FAMEM_MAPPING_PREFIX_SIZE 20U
#define FAMEM_MAPPING_EXTENT_SIZE 20U
#define FAMEM_EPOCH_RESPONSE_SIZE 8U

#endif
